#!/usr/bin/env ruby
# $ bundle exec bench_all

require 'scmd'

class AssertBenchCase

  ROOT = File.dirname(__FILE__)
  CMD  = "bundle exec #{ROOT}/bench"

  def initialize(case_data)
    @name = case_data[:name]
    @desc = case_data[:desc]

    @assert_dirs = Dir.glob("#{@name}/assert-*").reverse

    @results = []
  end

  def to_md
    table = @results.map do |r|
      "| #{r.version.rjust(13)} "\
      "| #{r.real_s.rjust(10)} "\
      "| #{r.user_s.rjust(10)} "\
      "| #{r.sys_s.rjust(10)} |\n"
    end.join

    "### #{@name}\n\n"\
    "#{@desc}\n\n"\
    "|    Version    | Real       | User       | Sys        |\n"\
    "| ------------- | ---------- | ---------- | ---------- |\n"\
    "#{table}\n"
  end

  def run
    puts @name

    dirs = @assert_dirs
    cmds = dirs.map do |d|
      { :version => d.split('/').last, :cmd => Scmd.new("#{CMD} #{d}") }
    end
    outs = cmds.map do |data|
      puts data[:cmd].to_s
      { :version => data[:version], :out => data[:cmd].run.stdout }
    end
    outs.inject(@results) do |results, data|
      res_s = data[:out].split("\n").last.split(/\s+/)
      @results << Result.new(data[:version], res_s[1], res_s[3], res_s[5])
    end

    puts
  end

  Result = Struct.new(:version, :real_s, :user_s, :sys_s)

end

CASES = [
  { :name => '01_basic',  :desc => "Suite of 2500 tests producing 3 passing results per test" },
]

begin
  folder = ARGV.first.to_s.gsub('/', '')
  cases = folder.empty? ? CASES : CASES.select{ |c| c[:name] == folder }
  puts cases.map{ |c| AssertBenchCase.new(c).tap(&:run).to_md }.join
rescue StandardError => exception
  $stderr.puts "#{exception.class}: #{exception.message}"
  $stderr.puts exception.backtrace.join("\n")
  exit(1)
end
exit(0)
